# Generated by Django 4.2.4 on 2023-09-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='delete',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
