# Generated by Django 4.2.4 on 2023-09-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='complate',
            field=models.BooleanField(default=False),
        ),
    ]
