# Generated by Django 4.2.4 on 2023-09-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_car_dislikes_remove_car_likes_remove_car_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='telegraph',
            field=models.URLField(default='https://telegra.ph/file/a2c29a823fb22433af042.jpg'),
        ),
    ]
