# Generated by Django 4.2.4 on 2023-09-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_carimage_telegraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='phone',
            field=models.CharField(default='-', max_length=15),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Joined'),
        ),
    ]
