# Generated by Django 4.2.4 on 2023-09-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_tguser_phone_alter_tguser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='post',
            field=models.BooleanField(default=False),
        ),
    ]
