# Generated by Django 4.2.4 on 2023-09-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_tguser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='telegraph',
            field=models.URLField(default='https://telegra.ph/file/6529587f8e3bd7a9b0c56.jpg'),
        ),
    ]
