# Generated by Django 4.2.4 on 2024-03-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_carimage_telegraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
